### ISSUE TITLE
function calls for frontend

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/SwarmCityAPI#14]
- [x]  I supply my public key, you supply my short code
- [x] I supply my public key, you supply my nonce
- [x]  I supply my public key, you supply my balance
- [x]  I connect, you supply the fx rates
- [x]  I supply another users short code, you supply their public key
- [x]  I supply my public key, you supply an array of transactions inc confirmation count
- [x]  I supply a signed transaction, you broadcast it

**Comment by bkawk** [comment]
1) The shortcode is correct in the wallet
2) I'm not getting nonce from `nonceChanged`
And I'm getting the value jof 500 from 
```                
// subscribe to updates of the nonce of this publickey
                socket.emit('subscribe', {
                    channel: 'nonce',
                    args: {
                        address: this.publickey,
                    },
                }, (reply) => {
                    console.log(reply); // response: 500
                    this.nonce = reply.data.nonce;
                    this.dispatch('NONCE', this.nonce);
                });
```
3) I am getting the balance but I have requested the format be changed to named objects
```
{
swt:{
      contractAddress: "0xb9e7f8568e08d5659f5d29c4997173d84cdf2607",
      balance(pin): "0",
},
arc:{
   contractAddress: "0xb9e7f8568e08d5659f5d29c4997173d84cdf2607",
    balance(pin): "0",
}
eth:{
   contractAddress: "0xb9e7f8568e08d5659f5d29c4997173d84cdf2607",
    balance(pin): "0",
}
}
```
4) The fx rate I am receiving please can we remove the underscores

**Comment by sponnet** [comment]
3 + 4 fixed in this PR https://github.com/swarmcity/SwarmCityAPI/pull/20
