### ISSUE TITLE
IPFS Hash to JSON

### ISSUE THREAD

**Issue by bkawk** [swarmcity/SwarmCityAPI#33]
I need to be able to send you an avatar hash `QmXxr6WpiGhDD83P5DdjyEXAxbxmNZg6CZ3Gsh3ARuAvc2` and get the JOSN back with the base64 of the image.

**Comment by sponnet** [comment]
https://github.com/swarmcity/SwarmCityAPI/tree/%2333_IPFS_Hash_to_JSON

**Comment by sponnet** [comment]
merged in master
