### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by koenedaele** [swarmcity/SwarmCityAPI#37]
The "test subscribe hashtags" is failing. It's failing on both branches I'm working on, but also on master.

> 1) Swarm City API socket client > test subscribe hashtags
>       should receive update to hashtags:
>     Error: Timeout of 180000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by sponnet** [comment]
You should run a local Eth node and point the. env file to it..

**Comment by koenedaele** [comment]
It fails on Travis too (at least for the branches). Shouldn't those tests work out of the box?

**Comment by sponnet** [comment]
They rely on an external server, defined here
https://github.com/swarmcity/SwarmCityAPI/blob/master/.travis.yml

**Comment by koenedaele** [comment]
So, either the Eth node at www.swarmdev.city is down or it is very slow?

**Comment by sponnet** [comment]
Could be, 

Ethpool.swarm.city is the old node, you can also use that if the other fails.

**Comment by BvL13** [comment]
Please clean up this issue and define which epic it belongs to or what the right label is.
