### ISSUE TITLE
Update Balance on New Block

### ISSUE THREAD

**Issue by bkawk** [swarmcity/SwarmCityAPI#48]
@vandaeko Each time a block is mined, the API needs to check the balance for each connected user, if the balance has changed we need to emit the balance changed to them.

**Comment by koenedaele** [comment]
From reading the code it seems like this is already how it should be functioning. Although this part of the tests has been commented out: https://github.com/koenedaele/SwarmCityAPI/blob/43d21a81b441aa2b94cac1b3f227449abcc4ab61/test/testPubsubBalance.js#L84

**Comment by koenedaele** [comment]
Having run more tests, (running the pubsubBalance functional test), it definitely looks like the balance updates are being tracked. I have no setup with a changing balance, but I don't see why that shouldn't work.

**Comment by sponnet** [comment]
It does
