### ISSUE TITLE
IPFS base64 Image not returning

### ISSUE THREAD

**Issue by bkawk** [swarmcity/SwarmCityAPI#57]
I have completed the request for the legacy IPFS base 64 image here https://github.com/swarmcity/SwarmCitySite/blob/%23449_legacy_avatar/src/data/socket-redux.html#L244-L258 but I don’t get a response back, please can you check I’m sending the correct object?

QmXxr6WpiGhDD83P5DdjyEXAxbxmNZg6CZ3Gsh3ARuAvc2
https://ipfs.swarm.city/ipfs/QmXxr6WpiGhDD83P5DdjyEXAxbxmNZg6CZ3Gsh3ARuAvc2

**Comment by koenedaele** [comment]
I checked the reply from the unit test (https://github.com/swarmcity/SwarmCityAPI/blob/master/test/testIpfsCat.js) and I see your avatar.

The calling code looks like this:
```javascript
it('should call ipfsCat with base64 encoding', function(done) {
		client.emit('ipfscat', {
			hash: 'QmXxr6WpiGhDD83P5DdjyEXAxbxmNZg6CZ3Gsh3ARuAvc2',
			format: 'base64',
		}, (reply) => {
			should(reply).have.property('response', 200);
			should(reply).have.property('data').and.be.a.String();
			done();
		});
	});
```

The avatar is in the reply.data property. I see you're dispatching the entire reply instead of reply.data?

**Comment by koenedaele** [comment]
Fixed in the Site, see https://github.com/swarmcity/SwarmCitySite/pull/547/files
