### ISSUE TITLE
Balance and FX seperation

### ISSUE THREAD

**Issue by bkawk** [swarmcity/SwarmCityAPI#61]
<img width="688" alt="screen shot 2018-02-01 at 9 56 13 am" src="https://user-images.githubusercontent.com/14357697/35669702-4e1f5188-0736-11e8-9686-cccd05074827.png">

**Comment by koenedaele** [comment]
Most of the logic aourd this is coming from https://github.com/swarmcity/SwarmCitySite/blob/1c5f5df93a16877e84c8421cc26fc65be11bee89/src/redux-state.html.

So it might be best to decide what should be handled where.

**Comment by BvL13** [comment]
Please clean up this issue and define which epic it belongs to.
