### ISSUE TITLE
Provide pubkey with rinkeby eth

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/SwarmCityAPI#77]
Sponnet says 0.1 ETH

**Comment by kingflurkel** [comment]
When a user connects to the api, the api checks the balance for that pub key. If the balance is lower than xx, the api sends xx eth to the pubkey from the faucet.

**Comment by koenedaele** [comment]
I assume this should only happen when the user is connected to Rinkeby. This can be checked in the environment variable NETWORK.

**Comment by kikipluche** [comment]
@koenedaele this issue needs some more attention first, hold your horses

**Comment by BvL13** [comment]
Please clean up this issue and define which epic it belongs to.
