### ISSUE TITLE
Make Rinkeby faucet

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/SwarmCityAPI#78]
Sponnet will reuse the code from the Ropsten faucet

**Comment by BvL13** [comment]
Is this part of an epic or a Labs topic?

**Comment by kikipluche** [comment]
it is part of an epic, because without it, we won’t be able to do transactions.

**Comment by BvL13** [comment]
Thanks for adding th epic. Thats all I was missing :o)

**Comment by sponnet** [comment]
It only has 10 ETH on it - so if you want to fund the faucet with a larger chunk of ETH , please send Rinkeby ETH to this address `0x687422eEA2cB73B5d3e242bA5456b782919AFc85`

**Comment by BvL13** [comment]
@sponnet can we move this to done? Or does it still need to be merged?
