### ISSUE TITLE
New response format for txHistory

### ISSUE THREAD

**Issue by koenedaele** [swarmcity/SwarmCityAPI#85]
The txHistory format should be changed to:

```
'transactionHash': '0x....' ( primary key )
'dateTime': <timestamp>
'direction': <'in'/'out'>
'amount': <in token units> ( 1e18 = 1 SWT )
'from': '0x....' 
'to': '0x....'
'block': <blocknumber where tx was mined>
'status': <0 => success , 1 => failure, 2 => pending>
```

**Comment by xardass** [comment]
New format:

`'transactionHash': '0x....' ( primary key )
'dateTime': <timestamp>
'direction': <'in'/'out'>
'amount': <in token units> ( 1e18 = 1 SWT )
'from': '0x....' 
'to': '0x....'
'block': <blocknumber where tx was mined>
'status': <0 => success , 1 => failure, 2 => pending>`

**Comment by eduadiez** [comment]
```
'transactionHash': '0x....' ( primary key )
'dateTime': <timestamp>
'direction': <'in'/'out'>
'amount': <in token units> ( 1e18 = 1 SWT )
'from': '0x....' 
'to': '0x....'
'block': <blocknumber where tx was mined>
'status': <0 => pending, 1 => success>
```

**Comment by BvL13** [comment]
@eduadiez is this one still work in progress and needed to finalize the terminal epics?
