### ISSUE TITLE
Impement txHistoryChanged 

### ISSUE THREAD

**Issue by xardass** [swarmcity/SwarmCityAPI#92]
Emit this format:

```
/**
 * Represents a txHistory change
 * @response
 */
{
    subscriptionId: <String>,
    txHistoryChanges: <Array of historyItems>
}
```

txHistoryChanges can be updates or new inserts (primary key is txHash ). An update could be an existing pending txHash changing state from pending to success.

- [ ] Data is an Array of historyItems
- [ ] Remove `confirmed` from response

**Comment by BvL13** [comment]
What epic does this belong to?
